CREATE TABLE USERDATA (
  ID LONG AUTO_INCREMENT  PRIMARY KEY,
  USER_ID VARCHAR(100) NOT NULL,
  USER_PW VARCHAR(15) NOT NULL,
  USER_ENC_SECRET VARCHAR(64) DEFAULT NULL,
  USER_ENC_KEY VARCHAR(44) DEFAULT NULL
);

INSERT INTO USERDATA (USER_ID, USER_PW) VALUES
  ('admin', '12345');
